// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AppHead: typeof import("./src/components/AppHead.vue")["default"];
    AppLink: typeof import("./src/components/AppLink.vue")["default"];
    ElAside: typeof import("element-plus/es")["ElAside"];
    ElContainer: typeof import("element-plus/es")["ElContainer"];
    ElDropdown: typeof import("element-plus/es")["ElDropdown"];
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
    ElFooter: typeof import("element-plus/es")["ElFooter"];
    ElHeader: typeof import("element-plus/es")["ElHeader"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElMain: typeof import("element-plus/es")["ElMain"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElMenuItemGroup: typeof import("element-plus/es")["ElMenuItemGroup"];
    ElScrollbar: typeof import("element-plus/es")["ElScrollbar"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    ElTable: typeof import("element-plus/es")["ElTable"];
    ElTableColumn: typeof import("element-plus/es")["ElTableColumn"];
    NavBar: typeof import("./src/components/NavBar.vue")["default"];
    SideNav: typeof import("./src/components/SideNav.vue")["default"];
    Table: typeof import("./src/components/Table.vue")["default"];
  }
}
